// constants/countries.ts

export interface Country {
  code: string // ISO 3166-1 alpha-2 (e.g., "KE")
  name: string // Official name (e.g., "Kenya")
  nationality: string // Demonym (e.g., "Kenyan")
}

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", nationality: "Afghan" },
  { code: "AL", name: "Albania", nationality: "Albanian" },
  { code: "DZ", name: "Algeria", nationality: "Algerian" },
  { code: "AO", name: "Angola", nationality: "Angolan" },
  { code: "AR", name: "Argentina", nationality: "Argentine" },
  { code: "AM", name: "Armenia", nationality: "Armenian" },
  { code: "AU", name: "Australia", nationality: "Australian" },
  { code: "AT", name: "Austria", nationality: "Austrian" },
  { code: "BD", name: "Bangladesh", nationality: "Bangladeshi" },
  { code: "BE", name: "Belgium", nationality: "Belgian" },
  { code: "BR", name: "Brazil", nationality: "Brazilian" },
  { code: "CA", name: "Canada", nationality: "Canadian" },
  { code: "CN", name: "China", nationality: "Chinese" },
  { code: "CD", name: "Democratic Republic of the Congo", nationality: "Congolese" },
  { code: "DK", name: "Denmark", nationality: "Danish" },
  { code: "EG", name: "Egypt", nationality: "Egyptian" },
  { code: "ET", name: "Ethiopia", nationality: "Ethiopian" },
  { code: "FI", name: "Finland", nationality: "Finnish" },
  { code: "FR", name: "France", nationality: "French" },
  { code: "DE", name: "Germany", nationality: "German" },
  { code: "GH", name: "Ghana", nationality: "Ghanaian" },
  { code: "GR", name: "Greece", nationality: "Greek" },
  { code: "IN", name: "India", nationality: "Indian" },
  { code: "ID", name: "Indonesia", nationality: "Indonesian" },
  { code: "IE", name: "Ireland", nationality: "Irish" },
  { code: "IL", name: "Israel", nationality: "Israeli" },
  { code: "IT", name: "Italy", nationality: "Italian" },
  { code: "JP", name: "Japan", nationality: "Japanese" },
  { code: "KE", name: "Kenya", nationality: "Kenyan" },
  { code: "MY", name: "Malaysia", nationality: "Malaysian" },
  { code: "MX", name: "Mexico", nationality: "Mexican" },
  { code: "MA", name: "Morocco", nationality: "Moroccan" },
  { code: "NL", name: "Netherlands", nationality: "Dutch" },
  { code: "NG", name: "Nigeria", nationality: "Nigerian" },
  { code: "NO", name: "Norway", nationality: "Norwegian" },
  { code: "PK", name: "Pakistan", nationality: "Pakistani" },
  { code: "PH", name: "Philippines", nationality: "Filipino" },
  { code: "PL", name: "Poland", nationality: "Polish" },
  { code: "PT", name: "Portugal", nationality: "Portuguese" },
  { code: "QA", name: "Qatar", nationality: "Qatari" },
  { code: "RU", name: "Russia", nationality: "Russian" },
  { code: "RW", name: "Rwanda", nationality: "Rwandan" },
  { code: "SA", name: "Saudi Arabia", nationality: "Saudi" },
  { code: "SG", name: "Singapore", nationality: "Singaporean" },
  { code: "ZA", name: "South Africa", nationality: "South African" },
  { code: "KR", name: "South Korea", nationality: "South Korean" },
  { code: "ES", name: "Spain", nationality: "Spanish" },
  { code: "SE", name: "Sweden", nationality: "Swedish" },
  { code: "CH", name: "Switzerland", nationality: "Swiss" },
  { code: "TZ", name: "Tanzania", nationality: "Tanzanian" },
  { code: "TH", name: "Thailand", nationality: "Thai" },
  { code: "TR", name: "Turkey", nationality: "Turkish" },
  { code: "UG", name: "Uganda", nationality: "Ugandan" },
  { code: "UA", name: "Ukraine", nationality: "Ukrainian" },
  { code: "AE", name: "United Arab Emirates", nationality: "Emirati" },
  { code: "GB", name: "United Kingdom", nationality: "British" },
  { code: "US", name: "United States", nationality: "American" },
  { code: "YE", name: "Yemen", nationality: "Yemeni" },
  { code: "ZM", name: "Zambia", nationality: "Zambian" },
  { code: "ZW", name: "Zimbabwe", nationality: "Zimbabwean" },
]
